name: diffusion-models
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - blas=1.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.3.11
  - expat=2.5.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - importlib-metadata=7.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libopenblas=0.3.27
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markdown=3.6
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.27
  - openssl=3.3.0
  - pip=23.3.1
  - python=3.12.2
  - re2=2022.04.01
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - tk=8.6.12
  - werkzeug=3.0.3
  - wheel=0.41.2
  - xz=5.4.6
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - accelerate==0.29.3
      - albumentations==1.4.4
      - annotated-types==0.6.0
      - anyio==4.3.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - av==12.0.0
      - babel==2.14.0
      - beartype==0.18.4
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - denoising-diffusion-pytorch==1.11.1
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - ema-pytorch==0.4.5
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.13.4
      - fonttools==4.51.0
      - fqdn==1.5.1
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - idna==3.7
      - imageio==2.34.0
      - ipykernel==6.29.4
      - ipython==8.23.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.0
      - joypy==0.2.6
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.26.0
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python-headless==4.9.0.80
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytorch-fid==0.3.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.0
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.34.0
      - regex==2024.4.16
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - safetensors==0.4.3
      - scikit-image==0.23.1
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - send2trash==1.8.3
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - tensorboardx==2.6.2.2
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - tifffile==2024.4.18
      - tinycss2==1.2.1
      - tokenizers==0.19.1
      - torch==2.2.2
      - torchdiffeq==0.2.3
      - torchsummary==1.5.1
      - torchvision==0.17.2
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - transformers==4.40.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - validators==0.28.1
      - wandb==0.16.6
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - widgetsnbextension==4.0.10
